services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    command: ["npm", "run", "dev"] # Use a dev script like nodemon for hot reloading
    networks:
      - CAREPRO_NETWORK

networks:
  CAREPRO_NETWORK:
    external: true
