version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - SECRET=$SECRET
      - PORT=$PORT
    stdin_open: true
    tty: true

volumes:
  db: