POST http://localhost:3000/api/doctors 
Content-Type: application/json


{
  "name": "John Doe Doctor",
  "email": "johndoeDoctor@example.com",
  "password": "password",
  "phoneNumber": "1234567890",
  "locality":"MAARIF Casablanca Morocco"
}