services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    networks:
      - CAREPRO_NETWORK

networks:
  CAREPRO_NETWORK:
    external: true
