version: "3.8"

services:
  postgresdb:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - CAREPRO_NETWORK

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - CAREPRO_NETWORK

  app:
    container_name: main_api
    depends_on:
      - postgresdb
    restart: unless-stopped
    build:
      context: .
    ports:
      - "3000:3000"
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - DB_HOST=postgresdb
      - DB_USER=$DB_USER
      - DB_NAME=$DB_NAME
      - SECRET=$SECRET
      - PORT=$PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/app # Mount your local src folder to /app inside the container
    command: ["npm", "run", "dev"] # Use a dev script like nodemon for hot reloading
    networks:
      - CAREPRO_NETWORK

networks:
  CAREPRO_NETWORK:
    external: true

volumes:
  db:
